### ISSUE TITLE
Fix `Error: Could not find node with given id`

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#275]
For `google.com` (and other sites):

```sh
Traversing the DOM{ Error: Could not find node with given id
    at /Users/alrra/projects/sonar/node_modules/chrome-remote-interface/lib/chrome.js:69:28
    at Chrome.handleMessage (/Users/alrra/projects/sonar/node_modules/chrome-remote-interface/lib/chrome.js:259:13)
    at WebSocket.<anonymous> (/Users/alrra/projects/sonar/node_modules/chrome-remote-interface/lib/chrome.js:236:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/Users/alrra/projects/sonar/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/alrra/projects/sonar/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/alrra/projects/sonar/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/alrra/projects/sonar/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:430:3)
    at onwrite (_stream_writable.js:421:7) code: -32000 }
(node:15569) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Could not find node with given id
(node:15569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
...
```

**Comment by sarvaje** [comment]
I've been taking a look to this issue and It looks like a problem with cdp, but I'm not sure. But I found a workaround: if you increase the collector options: waitFor, then you don't get the error.

For example, for the url: https://testpilot.firefox.com

With a `waitFor: 100` I get the error `Error: Could not find node with given id`
But if I increase the value to `1000` or `2000` then everything works fine.

**Comment by molant** [comment]
@sarvaje can you put an example of the output with the error?

**Comment by sarvaje** [comment]
sure thing, this is the error:
```
error: DOM.getOuterHTML
{ Error: Could not find node with given id
    at c:\github\MySonar\node_modules\chrome-remote-interface\lib\chrome.js:70:28
    at Chrome.handleMessage (c:\github\MySonar\node_modules\chrome-remote-interface\lib\chrome.js:260:13)
    at WebSocket.<anonymous> (c:\github\MySonar\node_modules\chrome-remote-interface\lib\chrome.js:237:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (c:\github\MySonar\node_modules\ws\lib\WebSocket.js:143:54)
    at Receiver.dataMessage (c:\github\MySonar\node_modules\ws\lib\Receiver.js:385:14)
    at extension.decompress (c:\github\MySonar\node_modules\ws\lib\Receiver.js:354:40)
    at _inflate.flush (c:\github\MySonar\node_modules\ws\lib\PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:430:3)
    at onwrite (_stream_writable.js:421:7) code: -32000 }
```

**Comment by alrra** [comment]
> With a waitFor: 100 I get the error Error: Could not find node with given id
> But if I increase the value to 1000 or 2000 then everything works fine.

Yes, using a higher value such as 1000, seems to fix the problem.
