### ISSUE TITLE
Fix `Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#388]
**Site:** msn.com
**Connector:** CDP

**Stack:**

```
...
  sonar:cli Failed to analyze: http://msn.com/ +2ms
  sonar:cli TypeError: Cannot read property 'nodeName' of undefined
  sonar:cli     at AsyncHTMLElement.get nodeName [as nodeName] (/Users/alrra/projects/sonar_/dist/src/lib/connectors/shared/async-html.js:108:33)
  sonar:cli     at Object.hasAttributeWithValue (/Users/alrra/projects/sonar_/dist/src/lib/utils/misc.js:110:28)
  sonar:cli     at CDPConnector.onResponseReceived (/Users/alrra/projects/sonar_/dist/src/lib/connectors/shared/remote-debugging-connector.js:233:20)
  sonar:cli     at <anonymous> +0ms
  sonar:connectors:shared:remote-debugging-connector Closing browsers used by CDP +0ms
  sonar:cli Total runtime: 12676ms +319ms
```

**Comment by molant** [comment]
Trying with http://mdn.com I can run sonar without issues but with https://mdn.com the process crashes.

Will open another issue for that and keep trying to reproduce the error under other circumstances.

**Comment by molant** [comment]
After investigating a bit, I think this happens when there is a request originated by an element that no longer exists in the DOM when we receive the response (maybe something for analytics?).

I'll update the code to not create a `AsyncHTMLElement` if no element can be found.

**Comment by qzhou1607** [comment]
Got a similar error:
connector: chrome
url: www.amazon.com
```
> @sonarwhal/sonar@0.4.0 site C:\github\Sonar.git
> node dist/src/bin/sonar "https://www.amazon.com/"

- https://images-na.ssl-i … 00x600._CB518489863_.jpg downloadedTypeError: Cannot read property 'nodeName' of undefined
    at AsyncHTMLElement.get nodeName [as nodeName] (C:\github\Sonar.git\dist\src\lib\connectors\shared\async-html.js:119:33)
    at Object.hasAttributeWithValue (C:\github\Sonar.git\dist\src\lib\utils\misc.js:159:28)
    at ChromeConnector.onResponseReceived (C:\github\Sonar.git\dist\src\lib\connectors\shared\remote-debugging-connector.js:272:20)
    at <anonymous>
× https://www.amazon.com/ … html/144-2965426-5832806 downloaded
Exit code: 1
```

**Comment by molant** [comment]
url: https://www.bing.com
connector: chrome
`Cannot read property 'nodeName' of undefined`
