### ISSUE TITLE
Cannot read property 'response' of undefined when accessing inexistant url

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#389]
**Url:** https://mdn.com
**Connector:** cdp

**Stack:**

```
TypeError: Cannot read property 'response' of undefined
    at CDPConnector.get headers [as headers] (c:\Projects\Sonar\src\lib\connectors\shared\remote-debugging-connector.ts:769:40)
    at Sonar.get pageHeaders [as pageHeaders] (c:\Projects\Sonar\src\lib\sonar.ts:52:31)
    at RuleContext.get pageHeaders [as pageHeaders] (c:\Projects\Sonar\src\lib\rule-context.ts:45:27)
    at validate (c:\Projects\Sonar\src\lib\rules\highest-available-document-mode\highest-available-document-mode.ts:173:47)
    at Immediate.setImmediate (c:\Projects\Sonar\src\lib\sonar.ts:176:51)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by molant** [comment]
Initial work of this is in https://github.com/sonarwhal/sonar/pull/390
