### ISSUE TITLE
SyntaxError when using jsdom

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#404]
Got this error when running sonar on `https://www.google.com`. The connector used was `jsdom`. This only happened when using `jsdom`.
```
/ Traversing the DOMSyntaxError
    at DocumentImpl.<anonymous> (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\living\nodes\ParentNode-impl.js:76:11)
    at DocumentImpl.querySelectorAll (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\utils.js:113:45)
    at Document.querySelectorAll (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\living\generated\ParentNode.js:52:45)
    at JSDOMAsyncHTMLDocument.querySelectorAll (C:\github\Sonar.git\dist\src\lib\connectors\jsdom\jsdom-async-html.js:12:68)
    at exports.findElementLocation (C:\github\Sonar.git\dist\src\lib\utils\location-helpers.js:45:50)
    at <anonymous>
- https://apis.google.com … ERAt_Iw/cb=gapi.loaded_0 downloaded
```

**Comment by sarvaje** [comment]
@qzhou1607 this error is due to a selector generated in the method `findElementLocation` line 57 in file `location-helpers.ts`
"traversing the dom" is just a previous message.

**Comment by sarvaje** [comment]
This error is back :(
This time is with the url `https://www.microsoft.com`.
