### ISSUE TITLE
Cannont read property 'outerHTML' of undefined on

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#465]
URL: https://sonarwhal.com
Connector: jsdom
Formatter: codeframe

```
Downloading https://cdn.jsdelivr.ne … ch.js/2/docsearch.min.jsTypeError: Cannot read property 'outerHTML' of undefined
    at JSDOMAsyncHTMLDocument.pageHTML (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\connectors\jsdom\jsdom-async-html.js:19:58)
    at Object.exports.findElementLocation (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\utils\location-helpers.js:44:46)
    at Object.exports.findProblemLocation (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\utils\location-helpers.js:105:43)
    at RuleContext.report (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\rule-context.js:71:49)
    at validate (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\rules\no-disallowed-headers\no-disallowed-headers.js:42:31)
    at Immediate.setImmediate [as _onImmediate] (C:\Users\antonmo\AppData\Local\nvs\node\8.4.0\x64\node_modules\@sonarwhal\sonar\dist\src\lib\sonar.js:133:46)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'outerHTML' of undefined
(node:17152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'outerHTML' of undefined
...
| https://fonts.googleapi … rrat:200,300,400,500,600 downloaded(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): TypeError: Cannot read property 'outerHTML' of undefined
(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): TypeError: Cannot read property 'outerHTML' of undefined
...
/ https://sonarwhal.com/images/iceberg-left.svg downloaded(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): TypeError: Cannot read property 'outerHTML' of undefined
(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 38): TypeError: Cannot read property 'outerHTML' of undefined
...
- https://sonarwhal.com/images/narwhal.svg downloaded(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 54): TypeError: Cannot read property 'outerHTML' of undefined
(node:17152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 56): TypeError: Cannot read property 'outerHTML' of undefined
...
```

Doesn't repro on `cdp`.
Changing the formatter to `stylish` produces also an invalid output but not as bad looking as the previous one.

**Comment by molant** [comment]
Can't repro it any more so closing for now. Will reopen if I can reproduce it consistently.
