### ISSUE TITLE
`no-vulnerable-javascript-libraries` crashes the process if semver is invalid

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#504]
**Site:** https://www.meetup.com/
**Connector:** chrome & jsdom

```bash 
$ npm run site -- meetup.com

> @sonarwhal/sonar@0.6.0 site /Users/alrra/projects/sonar_
> node dist/src/bin/sonar "meetup.com"

| Traversing finishedTypeError: Invalid Version: 2.0.1-pre -sizzle,-wrap,-event-alias,-effects,-dimensions,-deprecated
    at new SemVer (/Users/alrra/projects/sonar_/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/alrra/projects/sonar_/node_modules/semver/semver.js:1100:15)
    at Function.satisfies (/Users/alrra/projects/sonar_/node_modules/semver/semver.js:1149:16)
    at snykInfo.reduce (/Users/alrra/projects/sonar_/dist/src/lib/rules/no-vulnerable-javascript-libraries/no-vulnerable-javascript-libraries.js:127:32)
    at Array.reduce (native)
    at detectAndReportVulnerableLibraries (/Users/alrra/projects/sonar_/dist/src/lib/rules/no-vulnerable-javascript-libraries/no-vulnerable-javascript-libraries.js:126:50)
    at <anonymous>
```

**Comment by molant** [comment]
This is in the logic to detect vulnerable javascript libraries. If getting the semver fails then it crashes.
