### ISSUE TITLE
Process doesn't exit when `close` fails in `jsdom`

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#619]
When running this URL in online-service, `ssllabs` scan fails and a `timeout` error is reported. But when I run it in sonar, the scan results from `ssllab` was returned fairly quickly. Then I found that when running this URL in sonar, the process stays hanging and doesn't exit even though the failed `close` in jsdom is ignored and an `exitCode` of 0 is returned. I'm aware that it is relevant to https://github.com/sonarwhal/sonar/issues/203 and the pending requests don't matter. But I think `process.exit();` should be added to `run` (below) to force ending the process immediately if `close` fails, even though there are still pending requests. https://github.com/sonarwhal/sonar/blob/c997ef17dc196a6824eb28d8bc4e5023ef981fa9/src/bin/sonar.ts#L49-L54

## Environment

* __`sonar` version:__ 0.13.0
* __`Node.js` version:__ 8.8.0
* __`npm` version:__  5.3.0

## `sonar` configuration

<details>
<summary>sonar's configuration</summary>

```js

{
    "connector": {
        "name": "jsdom",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": "stylish",
    "rulesTimeout": 120000,
    "rules": {
        "amp-validator": "warning",
        "apple-touch-icons": "off",
        "axe": "off",
        "content-type": "off",
        "disown-opener": "off",
        "highest-available-document-mode": "off",
        "html-checker": "off",
        "manifest-exists": "off",
        "manifest-file-extension": "off",
        "manifest-is-valid": "off",
        "meta-charset-utf-8": "off",
        "no-disallowed-headers": "off",
        "no-friendly-error-pages": "off",
        "no-html-only-headers": "off",
        "no-protocol-relative-urls": "off",
        "no-vulnerable-javascript-libraries": "off",
        "ssllabs": "warning",
        "strict-transport-security": "off",
        "x-content-type-options": "off",
        "validate-set-cookie-header": "off"
    }
}


```

</details>

## URL for which `sonar` failed

* __URL:__ http://www.toutiao.com

## Output

Please include the raw output generated by `sonar`, or if possible,
the raw output from running `sonar` in debug mode: `sonar --debug <URL>`.

<details>
<summary>sonar's raw output</summary>

```text
✖ Found a total of 0 errors and 25 warnings
  sonar:connectors:jsdom Exception ignored while closing JSDOM connector (most likely pending network requests) +7s
  sonar:connectors:jsdom TypeError: openedRequest.abort is not a function
  sonar:connectors:jsdom     at RequestManager.close (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:14
7:21)
  sonar:connectors:jsdom     at Window.close (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\browser\Window.js:375:29)
  sonar:connectors:jsdom     at JSDOMConnector.close (C:\github\Sonar.git\dist\src\lib\connectors\jsdom\jsdom.js:371:26)
  sonar:connectors:jsdom     at Sonar.close (C:\github\Sonar.git\dist\src\lib\sonar.js:192:30)
  sonar:connectors:jsdom     at exports.analyze (C:\github\Sonar.git\dist\src\lib\cli\analyze.js:139:25)
  sonar:connectors:jsdom     at <anonymous>
  sonar:connectors:jsdom     at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
  sonar:cli:analyze Total runtime: 25081ms +27s
Exit code: 0
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +13s
  sonar:connectors:jsdom resource https://c.cnzz.com/core.php?web_id=1259612802&t=z fetched +6s
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +4ms
  sonar:connectors:jsdom resource https://z4.cnzz.com/stat.htm?id=1259612802&r=&lg=en-us&ntime=none&cnzz_eid=689302160-1509555781-&show
p=0x0&t=%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1&umuuid=15f78db25d3457-0211416ef1db1e-5b141279-0-15f78db25d42f0&h=1&rnd=1333901373 fetched
+5ms
  sonar:connectors:jsdom resource https://cnzz.mmstat.com/9.gif?abc=1&rnd=1181025029 to be fetched +6ms
  sonar:connectors:jsdom resource http://jserr.cnzz.com/log.php?siteid=1259612802&name=TypeError&msg=Cannot%20read%20property%20%27inse
rtBefore%27%20of%20null&r=&page=https%3A%2F%2Fwww.toutiao.com%2F&agent=Node.js%20(win32%3B%20U%3B%20rv%3Av8.8.0)%20AppleWebKit%2F537.36
%20(KHTML%2C%20like%20Gecko)&ex=cI%20failed&rnd=1047321395 to be fetched +10ms
  sonar:connectors:utils:requester Requesting https://cnzz.mmstat.com/9.gif?abc=1&rnd=1181025029 +14s
  sonar:connectors:utils:requester Requesting http://jserr.cnzz.com/log.php?siteid=1259612802&name=TypeError&msg=Cannot%20read%20proper
ty%20%27insertBefore%27%20of%20null&r=&page=https%3A%2F%2Fwww.toutiao.com%2F&agent=Node.js%20(win32%3B%20U%3B%20rv%3Av8.8.0)%20AppleWeb
Kit%2F537.36%20(KHTML%2C%20like%20Gecko)&ex=cI%20failed&rnd=1047321395 +5ms
  sonar:connectors:jsdom resource https://show-g.mediav.com/s?jsonp=_qihu_jsonpFun_&type=1&of=4&newf=1&showid=P5AcFE&ref=toutiao.com&ui
d=15095611545182674181990003437423&scheme=https&impct=5&time=ts_1509561172552 to be fetched +19ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561172555 to be fetched +2ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561172564 to be fetched +11ms
  sonar:connectors:utils:requester Requesting https://show-g.mediav.com/s?jsonp=_qihu_jsonpFun_&type=1&of=4&newf=1&showid=P5AcFE&ref=to
utiao.com&uid=15095611545182674181990003437423&scheme=https&impct=5&time=ts_1509561172552 +3s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561172555 +1ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561172564 +1ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +4s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561154521 fetched +3s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +6ms
  sonar:connectors:jsdom resource https://s3a.pstatp.com/toutiao/picc_mig/dist/img.min.js?ver=20171101_01 fetched +7ms
  sonar:connectors:jsdom resource https://ei.cnzz.com/stat.htm?id=1259612802&r=&lg=en-us&ntime=none&cnzz_eid=689302160-1509555781-&show
p=0x0&ei=ad-script%7Cindex%7Cload%7C1%7C&t=%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1&umuuid=15f78db25d3457-0211416ef1db1e-5b141279-0-15f78db
25d42f0&h=1&rnd=1980859824 to be fetched +36ms
  sonar:connectors:utils:requester Requesting https://ei.cnzz.com/stat.htm?id=1259612802&r=&lg=en-us&ntime=none&cnzz_eid=689302160-1509
555781-&showp=0x0&ei=ad-script%7Cindex%7Cload%7C1%7C&t=%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1&umuuid=15f78db25d3457-0211416ef1db1e-5b1412
79-0-15f78db25d42f0&h=1&rnd=1980859824 +60ms
  sonar:connectors:utils:requester Redirect found for https://cnzz.mmstat.com/9.gif?abc=1&rnd=1181025029 +396ms
  sonar:connectors:utils:requester Requesting http://www.taobao.com/ +4ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +472ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561154525 fetched +435ms
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +1ms
  sonar:connectors:jsdom resource https://www.toutiao.com/ fetched +2ms
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +103ms
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/43d60001fc6786630b03 fetched +103ms
  sonar:connectors:utils:charset Content Type 'image/gif' doesn't require decoding +13ms
  sonar:connectors:jsdom resource http://jserr.cnzz.com/log.php?siteid=1259612802&name=TypeError&msg=Cannot%20read%20property%20%27inse
rtBefore%27%20of%20null&r=&page=https%3A%2F%2Fwww.toutiao.com%2F&agent=Node.js%20(win32%3B%20U%3B%20rv%3Av8.8.0)%20AppleWebKit%2F537.36
%20(KHTML%2C%20like%20Gecko)&ex=cI%20failed&rnd=1047321395 fetched +13ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +6ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561172564 fetched +5ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +1ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561172555 fetched +2ms
  sonar:connectors:utils:requester Redirect found for http://www.taobao.com/ +566ms
  sonar:connectors:utils:requester Requesting https://www.taobao.com/ +6ms
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +539ms
  sonar:connectors:jsdom resource https://show-g.mediav.com/s?jsonp=_qihu_jsonpFun_&type=1&of=4&newf=1&showid=P5AcFE&ref=toutiao.com&ui
d=15095611545182674181990003437423&scheme=https&impct=5&time=ts_1509561154518 fetched +551ms
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +24ms
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/3f01002107bd8587e2f7 fetched +12ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561177208 to be fetched +10ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561177211 to be fetched +3ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561177208 +5s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561177211 +2ms
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +5s
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/3f0200227fa3645a70bb fetched +5s
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +5ms
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/3f05000251ce7feeabed fetched +4ms
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +2ms
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/3f0200227eb3bb82d852 fetched +2ms
  sonar:connectors:utils:charset Content Type 'image/jpeg' doesn't require decoding +6ms
  sonar:connectors:jsdom resource https://p3.pstatp.com/origin/43d5000238f4b6486779 fetched +7ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=vxm1yc6kr150
9561148901&type=event&t=1509561182484 to be fetched +5ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=
vxm1yc6kr1509561148901&type=event&t=1509561182484 +29ms
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +21ms
  sonar:connectors:jsdom resource https://show-g.mediav.com/s?jsonp=_qihu_jsonpFun_&type=1&of=4&newf=1&showid=P5AcFE&ref=toutiao.com&ui
d=15095611545182674181990003437423&scheme=https&impct=5&time=ts_1509561172552 fetched +18ms
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +214ms
  sonar:connectors:jsdom resource https://ei.cnzz.com/stat.htm?id=1259612802&r=&lg=en-us&ntime=none&cnzz_eid=689302160-1509555781-&show
p=0x0&ei=ad-script%7Cindex%7Cload%7C1%7C&t=%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1&umuuid=15f78db25d3457-0211416ef1db1e-5b141279-0-15f78db
25d42f0&h=1&rnd=1980859824 fetched +212ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +242ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561177208 fetched +242ms
  sonar:connectors:utils:requester Redirect found for https://www.taobao.com/ +471ms
  sonar:connectors:utils:requester Requesting https://world.taobao.com/ +0ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +63ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561177211 fetched +64ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +83ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=vxm1yc6kr150
9561148901&type=event&t=1509561182484 fetched +86ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561183371 to be fetched +265ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561183374 to be fetched +3ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561183371 +5s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561183374 +1ms
  sonar:connectors:utils:charset Charset for 'text/html; charset=utf-8' is 'utf-8' +6s
  sonar:connectors:jsdom resource https://cnzz.mmstat.com/9.gif?abc=1&rnd=1181025029 fetched +6s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=vxm1yc6kr150
9561148901&type=event&t=1509561188965 to be fetched +7ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=
vxm1yc6kr1509561148901&type=event&t=1509561188965 +549ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +210ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561183371 fetched +211ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +66ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561183374 fetched +60ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561189285 to be fetched +49ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561189303 to be fetched +18ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561189285 +6s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561189303 +2ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +6s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=feed_qihu_adshow_count&ext_id=5&sid=vxm1yc6kr150
9561148901&type=event&t=1509561188965 fetched +6s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +513ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561189303 fetched +512ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +38ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561189285 fetched +39ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561196175 to be fetched +342ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561196177 to be fetched +2ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561196175 +6s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561196177 +1ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +6s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561196177 fetched +5s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +20ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561196175 fetched +19ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561201974 to be fetched +371ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561201979 to be fetched +6ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561201974 +7s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561201979 +7ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +7s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561201979 fetched +7s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +5ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561201974 fetched +5ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561209348 to be fetched +409ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561209353 to be fetched +5ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561209348 +8s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1
yc6kr1509561148901&type=event&t=1509561209353 +1ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +8s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561209348 fetched +8s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +103ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=8&sid=vxm1yc6kr1509561
148901&type=event&t=1509561209353 fetched +101ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561217428 to be fetched +241ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561217431 to be fetched +3ms
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561217428 +6s
  sonar:connectors:utils:requester Requesting https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1
yc6kr1509561148901&type=event&t=1509561217431 +1ms
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +6s
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561217428 fetched +6s
  sonar:connectors:utils:charset No 'charset' defined, falling back to 'utf-8' +49ms
  sonar:connectors:jsdom resource https://www.toutiao.com/api/article/user_log/?c=/&ev=article_show_count&ext_id=7&sid=vxm1yc6kr1509561
148901&type=event&t=1509561217431 fetched +49ms


```

</details>

**Comment by molant** [comment]
This is what I'm proposing in https://github.com/sonarwhal/sonar/issues/585#issuecomment-340509376 😉

I'll close this issue in favor of #585.
